apiVersion: v1
kind: Service
metadata:
  name: suspicious-events-detector
  namespace: suspicious-events-detector
spec:
  type: NodePort
  selector:
    app: suspicious-events-detector
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
