apiVersion: v1
kind: Secret
metadata:
  name: suspicious-events-detector-secret
  namespace: suspicious-events-detector
type: Opaque
stringData:
  MYSQL_USERNAME: "detector-user"
  MYSQL_PASSWORD: "detector-pass"
