apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: suspicious-events-detector
resources:
  - namespace.yaml
  - mysql-secret.yaml
  - mysql-statefulset.yaml
  - mysql-service.yaml
  - app-configmap.yaml
  - app-secret.yaml
  - app-deployment.yaml
  - app-service.yaml
images:
  - name: docker.io/yaseenasaliya/suspicious-events-detector
    newTag: latest
