apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: suspicious-events-detector
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root-demo-pass"
  MYSQL_USER: "detector-user"
  MYSQL_PASSWORD: "detector-pass"
